### ISSUE TITLE
Working within Devise

### ISSUE THREAD

**Issue by wprater** [opperator/warden-oauth2#6]
Trying to get this strategy working with Devise, but I cannot seem to get any of the Devise controllers to auth with this strategy.  It does work fine within my Grape App that is mounted into Rails.

Here is what my config for Devise looks like

```
  config.warden do |manager|
    manager.strategies.add(:public, Warden::OAuth2::Strategies::Public)
    manager.strategies.add(:bearer, Warden::OAuth2::Strategies::Bearer)
    manager.default_strategies(scope: :user).unshift(:bearer)
    manager.default_strategies(:bearer)

    manager.failure_app = ThorApi::OAuth2::FailureApp
  end
```

And this is what the warden instance inspects as while in the failure app hitting a route in Devise.

```
Warden::Proxy:70349065951920 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:bearer, :rememberable, :database_authenticatable], :_all=>[:bearer]}, :intercept_401=>false, :failure_app=>ThorApi::OAuth2::FailureApp}
```

Ideas of what I might have setup incorrectly?

**Comment by kidpollo** [comment]
This is what my config looks like.

Hope it helps. but I dont use Devise oh and I have a slightly patched version of this lib. 

I would recommend you dont use devise if you can separate your api as a separate thing.

``` ruby
require 'unauthorized_app'

Warden::OAuth2.configure do |config|
  config.client_model = ClientApplication
  config.token_model  = AccessToken
end

Warden::Strategies.add(:bearer, Warden::OAuth2::Strategies::Bearer)
Warden::Strategies.add(:client, Warden::OAuth2::Strategies::Client)

Rails.configuration.middleware.use Warden::Manager do |manager|
  manager.default_strategies :bearer, :client
  manager.failure_app = Services::UnauthorizedApp
  manager.intercept_401 = false
end
```

**Comment by wprater** [comment]
I would prefer not to use devise as well, but I've modified it to only allow json requests and responses.  I like that devise provides registrations, invitations, confirmations, tracking, etc. and didn't want to build that in another library.  Do you know of another library that would help with those features?

**Comment by kidpollo** [comment]
Well in our case we have a different app that does that. There is no reason to have it in the same app. You can do rails engines if you want to use the same repo. As we have it right now user registration and key management are a separate concern and are provided by separate services as it should :P

**Comment by wprater** [comment]
Im going to pull them apart later, but issue Im having is still going to persist, Im afraid.  I think the issue is the scope I have setup in my OAuth2 server is :api and the scope being used/setup in Devise is :user.  I don't know enough about Devise to change this.  Obviously this is not an issue for this project.  If you have ideas on Devise though, Im open ears!

**Comment by derrimahendra** [comment]
Maybe it's a bit late but I found this one work on mine.

```
config.warden do |manager|
  manager.strategies.add :bearer, Warden::OAuth2::Strategies::Bearer
  manager.strategies.add :client, Warden::OAuth2::Strategies::Client

  manager.scope_defaults :api, strategies: [:bearer, :client], failure_app: YourCustom::FailureApp #this one for api
end
```

and add some change on devise delegator

```
module Devise
  class Delegator
    def call(env)
      failure_app(env).call(env)
    end

    def failure_app(env)
      app = env["warden.options"] &&
        (scope = env["warden.options"][:scope]) &&
          ((Devise.mappings[scope.to_sym] &&
            Devise.mappings[scope.to_sym].failure_app) or env["warden.options"][:failure_app])

      app || Devise::FailureApp
    end
  end
end
```
